### PR TITLE
Add flag for which node module to build

### PR DESCRIPTION
**Pull request by maxkorp**
I've added a flag `-w` to allow this to rebuild a single module, if you so choose. Otherwise, it still just rebuilds everything like before. See #26.

### CODE REVIEW

**Comment by paulcbetts** [comment]
Thanks @maxkorp!

**Comment by maxkorp** [comment]
@paulcbetts Any chance of getting a build published now that this is in? Using it as a build dependency and I'd like to just keep it to a simple npm install.

**Comment by paulcbetts** [comment]
@maxkorp Done, this is 1.0.2

**Comment by maxkorp** [comment]
Awesome, thanks a ton dude. Just fyi doesn't look like the bump or tag got pushed to github.

**Comment by paulcbetts** [comment]
@maxkorp Fixed

**Pull request merged**
