### PR TITLE
Pass --runtime when calling npm

### PR DESCRIPTION
**Pull request by zcbenz**
Refs https://github.com/mapbox/node-pre-gyp/pull/175.

### CODE REVIEW

**Comment by paulcbetts** [comment]
Thanks @zcbenz!

**Comment by paulcbetts** [comment]
@zcbenz This is published as 1.0.1

**Comment by sheerun** [comment]
@paulcbetts Please remember to tag and push :)

**Comment by paulcbetts** [comment]
hwhoops, fixed! Thanks @sheerun

**Pull request merged**
